# Generated by Django 4.0 on 2021-12-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='co2web',
            fields=[
                ('url', models.CharField(default='', max_length=10000, primary_key=True, serialize=False)),
                ('co2', models.FloatField(default=0.0)),
                ('date', models.CharField(default='', max_length=100)),
                ('green_web', models.BooleanField(default=False)),
                ('cleaner_than', models.IntegerField(default=0)),
                ('co2_equivalent', models.FloatField(default=0.0)),
                ('sumo_weight', models.FloatField(default=0.0)),
                ('cups', models.IntegerField(default=0)),
                ('tree', models.IntegerField(default=0)),
                ('energy', models.FloatField(default=0.0)),
                ('car_distance', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('msg1', models.CharField(default='', max_length=100)),
                ('msg2', models.CharField(default='', max_length=100)),
                ('msg3', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
